"""
Django settings for crash_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from Backend/.env (works even if the process is
# started from a different working directory).
load_dotenv(dotenv_path=BASE_DIR / '.env')


def _env_str(name: str, default: str | None = None) -> str | None:
    value = os.getenv(name, default)
    if not isinstance(value, str):
        return value
    value = value.strip()
    if (len(value) >= 2) and ((value[0] == value[-1]) and value[0] in ("'", '"')):
        value = value[1:-1]
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'SECRET_KEY'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'corsheaders',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crash_backend.urls'

# CORS Configuration - Allow Frontend to Call Backend
# Updated for Vite dev server (port 5173) and production URLs
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",      # Vite dev server (React)
    "http://127.0.0.1:5173",      # Alternative localhost

    "http://localhost:5174",
    "http://localhost:5175",
    "http://127.0.0.1:5174", 
    "http://127.0.0.1:5175", 

    # Add production URLs when deploying:
    # "https://your-frontend-domain.com",
]

# Allow credentials (cookies, auth headers) in CORS requests
# Required for JWT tokens in Authorization header
CORS_ALLOW_CREDENTIALS = True


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'pdf-templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crash_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Under DATABASES, ensure the password is still hardcoded for now, but use this for the API Key:
GOOGLE_MAPS_API_KEY = _env_str('GOOGLE_MAPS_API_KEY')
SECRET_KEY = _env_str('SECRET_KEY')

# Supabase SDK Settings
SUPABASE_URL = _env_str('SUPABASE_URL')
SUPABASE_SERVICE_ROLE_KEY = _env_str('SUPABASE_SERVICE_ROLE_KEY')

# REST Framework Configuration
REST_FRAMEWORK = {
    # Disable default authentication - we validate JWT tokens manually in views
    # This prevents the auto-lookup of Django User model which conflicts with our
    # PoliceOffice model (UUID vs integer primary key mismatch)
    
    # Datetime format:
    # Use DRF's ISO-8601 output (includes timezone info like 'Z' or '+08:00').
    # This prevents JS from misreading naive timestamps as local time.
    'DATETIME_FORMAT': 'iso-8601',
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    # Most endpoints don't require auth by default (public access for citizens)
    # Individual views/viewsets can override with permission_classes
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# JWT Configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),  # Token valid for 24 hours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),   # Refresh valid for 7 days
    'ROTATE_REFRESH_TOKENS': True,                 # Generate new refresh on use
    'BLACKLIST_AFTER_ROTATION': False,             # Don't blacklist old tokens (simpler)
    'AUTH_HEADER_TYPES': ('Bearer',),              # Authorization: Bearer <token>
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True

# Cache Configuration for Lock Mechanism
# Uses in-memory cache for analytics update lock
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-cache',
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

